"""Planner agent deciding high-level memory actions."""
from __future__ import annotations

from dataclasses import dataclass
from typing import List, Sequence, Tuple

from simulator.environment import EnvironmentState


@dataclass
class Plan:
    """Plan generated by the planner agent."""

    preload: List[str]
    keep: List[str]


class PlannerAgent:
    """Selects which apps to preload based on predictions and memory state."""

    def plan(self, predictions: Sequence[Tuple[str, float]], state: EnvironmentState) -> Plan:
        """Create a plan to preload the top predicted apps not already loaded."""
        loaded = set(state.loaded_apps)
        preload = [app for app, _ in predictions if app not in loaded]
        return Plan(preload=preload, keep=state.loaded_apps)
